//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbBus.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbBusEntities : DbContext
    {
        public AbBusEntities()
            : base("name=AbBusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<master_city> master_city { get; set; }
        public virtual DbSet<master_station> master_station { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<bus> buses { get; set; }
        public virtual DbSet<itinerary> itineraries { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<trip> trips { get; set; }
    }
}
