//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbBus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class itinerary
    {
        public int ID { get; set; }
        public int TripID { get; set; }
        public int Stop { get; set; }
        public int StopSequence { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public int Fare { get; set; }
    
        public virtual master_station master_station { get; set; }
        public virtual trip trip { get; set; }
    }
}
