//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbBus.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seat()
        {
            this.bookings = new HashSet<booking>();
            this.bookings1 = new HashSet<booking>();
        }
    
        public int ID { get; set; }
        public int BusId { get; set; }
        public string Number { get; set; }
        public string Type { get; set; }
        public int Occupancy { get; set; }
        public bool IsLower { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings1 { get; set; }
        public virtual bus bus { get; set; }
    }
}
